### ISSUE TITLE
Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by igroykt** [Restream/redmine_tagging#52]
I have some error:
Completed 500 Internal Server Error in 5245ms

ActiveRecord::StatementInvalid (Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `issues` SET `project_id` = 46, `fixed_version_id` = 164, `updated_on` = '2014-12-30 15:52:20', `lock_version` = 2 WHERE (`issues`.`id` = 35127 AND `issues`.`lock_version` = 1)):
  app/models/issue.rb:159:in `create_or_update'
  app/controllers/issues_controller.rb:270:in `block in bulk_update'
  app/controllers/issues_controller.rb:259:in `each'
  app/controllers/issues_controller.rb:259:in `bulk_update'

innodb_table_locks=off didnt solve the problem.

Environment:
  Redmine version                2.3.3.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  redmine_embedded_video         0.0.3.1
  redmine_importer               1.0
  redmine_lightbox               0.0.1
  redmine_tagging                0.1.2

Server version: 10.0.10-MariaDB MariaDB Server

One more thing: by default tables was in latin1 collation so i converted them info utf8_general. I hope the problem is not because of this.

**Comment by igroykt** [comment]
Got something today:
Started GET "/plugin_assets/redmine_tagging/javascripts/jquery_loader.js" for 127.0.0.1 at 2015-04-15 09:26:55 +0900

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_tagging/javascripts/jquery_loader.js"):
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  thin (1.6.1) lib/thin/connection.rb:82:in `block in pre_process'
  thin (1.6.1) lib/thin/connection.rb:80:in `catch'
  thin (1.6.1) lib/thin/connection.rb:80:in `pre_process'
  thin (1.6.1) lib/thin/connection.rb:55:in `process'
  thin (1.6.1) lib/thin/connection.rb:41:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.1) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.1) lib/thin/server.rb:162:in `start'
  thin (1.6.1) lib/thin/controllers/controller.rb:87:in `start'
  thin (1.6.1) lib/thin/runner.rb:200:in `run_command'
  thin (1.6.1) lib/thin/runner.rb:156:in `run!'
  thin (1.6.1) bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<main>'

Is that means that i need to install jquery gem?
