### ISSUE TITLE
db_migrate plugins issue - context does not exist

### ISSUE THREAD

**Issue by yelha** [Restream/redmine_tagging#75]
Hello! 

First of all thank you for the plugin. 
I followed the steps for the plugin installation and have an issue with the db:migrate_plugins task.

Environment:

`Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
  GitRemote                      2.1.4
Redmine plugins:
  ajax_counters                  1.4.0
  clipboard_image_paste          1.10
  easy_wbs                       2016-0.0
  redmine_agile                  1.4.4
  redmine_checklists             3.1.5
  redmine_default_assign         0.6
  redmine_dmsf                   1.5.8
  redmine_favorite_projects      2.0.3
  redmine_git_remote             0.0.1
  redmine_gitlab_hook            0.1.3
  redmine_issue_templates        0.1.6
  redmine_people                 1.2.0
  redmine_tagging                0.1.6
  redmine_work_time              0.3.3
  sidebar_hide                   0.0.8`

Issue:

`rake db:migrate_plugins RAILS_ENV=production
Migrating redmine_tagging (Redmine Tagging Plugin)...
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "context" does not exist
LINE 1: ... where taggable_type in ('WikiPage', 'Issue') and context in...
                                                             ^
: SELECT "tags".* FROM "tags" WHERE (not name like '#%' and id in (select tag_id from taggings where taggable_type in ('WikiPage', 'Issue') and context in ('********* - masked as internal product names')))
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:39:in `find_by_sql'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in `exec_queries'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in `to_a'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/redmine-3.3.2/plugins/redmine_tagging/db/migrate/20161031000002_scrub_body.rb:25:in `<class:ScrubBody>'
/opt/redmine-3.3.2/plugins/redmine_tagging/db/migrate/20161031000002_scrub_body.rb:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:777:in `load_migration'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:773:in `migration'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:958:in `block in migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.3.2/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.3.2/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.3.2/lib/redmine/plugin.rb:467:in `block in migrate'
/opt/redmine-3.3.2/lib/redmine/plugin.rb:466:in `each'
/opt/redmine-3.3.2/lib/redmine/plugin.rb:466:in `migrate'
/opt/redmine-3.3.2/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/var/lib/gems/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
PG::UndefinedColumn: ERROR:  column "context" does not exist
LINE 1: ... where taggable_type in ('WikiPage', 'Issue') and context in...
`
The plugin itself shows up after redmine restart. Not tested yet if everything is fine, just wondering about the error.

Please be patient if I am doing something wrong, it is my first issue opened. 

Thank you for your help!

**Comment by nodecarter** [comment]
Hell @yelha , 
It seems that migration of acts-as-taggable-on was not successful. 
Did you run `bundle exec rake acts_as_taggable_on_engine:install:migrations RAILS_ENV=production` ?
And was it successful?

**Comment by yelha** [comment]
Hi! Thanks for the quick reply. 

Just installed again following the steps and this task was ok. But the next one failed now:


```
redmine@vr-vm-redmine-sandbox01:/opt/redmine$ bundle install
....
Using redmine_extensions 0.1.27
Bundle complete! 51 Gemfile dependencies, 73 gems now installed.
....
redmine@vr-vm-redmine-sandbox01:/opt/redmine$ bundle exec rake acts_as_taggable_on_engine:install:migrations RAILS_ENV=production
redmine@vr-vm-redmine-sandbox01:/opt/redmine$ bundle exec rake db:migrate RAILS_ENV=production
== 20170718141210 ActsAsTaggableOnMigration: migrating ========================
-- create_table(:tags)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "tags" already exists
: CREATE TABLE "tags" ("id" serial primary key, "name" character varying) 
/var/lib/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'

```

**Comment by nodecarter** [comment]
Hm. Maybe some other plugin creates such table `tags` or you have a duplicated migrations. 
You can search in migrations in redmine and plugins for creating table `tags`.

**Comment by yelha** [comment]
Thanks a lot for your help
