### ISSUE TITLE
3.4.2.stable error 

### ISSUE THREAD

**Issue by keithkuk** [Restream/redmine_tagging#76]
Migrating redmine_tagging (Redmine Tagging Plugin)...
== 20161031000001 CreateViews: migrating ======================================
-- execute("DROP VIEW IF EXISTS issue_tags")
   -> 0.0002s
-- execute("      CREATE VIEW issue_tags AS\n      SELECT\n        taggings.id AS id,\n        tags.name AS tag,\n        taggings.taggable_id AS issue_id\n      FROM\n        taggings\n          JOIN tags ON taggings.tag_id = tags.id\n      WHERE\n        taggable_type = 'Issue'\n")
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'redmine.taggings' doesn't exist:       CREATE VIEW issue_tags AS
      SELECT
        taggings.id AS id,
        tags.name AS tag,
        taggings.taggable_id AS issue_id
      FROM
        taggings
          JOIN tags ON taggings.tag_id = tags.id
      WHERE
        taggable_type = 'Issue'

/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/www/html/redmine/plugins/redmine_tagging/db/migrate/20161031000001_create_views.rb:5:in `up'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/html/redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/html/redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/html/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redmine.taggings' doesn't exist:       CREATE VIEW issue_tags AS
      SELECT
        taggings.id AS id,
        tags.name AS tag,
        taggings.taggable_id AS issue_id
      FROM
        taggings
          JOIN tags ON taggings.tag_id = tags.id
      WHERE
        taggable_type = 'Issue'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/www/html/redmine/plugins/redmine_tagging/db/migrate/20161031000001_create_views.rb:5:in `up'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/html/redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/html/redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/html/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Mysql2::Error: Table 'redmine.taggings' doesn't exist
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/www/html/redmine/plugins/redmine_tagging/db/migrate/20161031000001_create_views.rb:5:in `up'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/html/redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/var/www/html/redmine/lib/redmine/plugin.rb:466:in `each'
/var/www/html/redmine/lib/redmine/plugin.rb:466:in `migrate'
/var/www/html/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate

**Comment by koelle25** [comment]
+1
When trying to view spent times it goes into an internal server error.
I have tested it with redmine_tagging plugin only, too (no other plugins). Same error.

The **production log** states:
```
Started GET "/projects/idial-server/time_entries" for 192.168.0.254 at 2017-07-28 15:17:40 +0200
Processing by TimelogController#index as HTML
  Parameters: {"project_id"=>"idial-server"}
  Current user: kevin.koellmann (id=8)
  Rendered queries/_filters.html.erb (4.0ms)
  Rendered queries/_query_form.html.erb (4.3ms)
  Rendered timelog/_date_range.html.erb (4.4ms)
  Rendered timelog/index.html.erb within layouts/base (4.8ms)
Completed 500 Internal Server Error in 41ms (ActiveRecord: 11.5ms)

ActionView::Template::Error (undefined method `remote' for #<Hash:0x007fb44f144280>):
    1: <%= javascript_tag do %>
    2: var operatorLabels = <%= raw_json Query.operators_labels %>;
    3: var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
    4: var availableFilters = <%= raw_json query.available_filters_as_json %>;
    5: var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
    6:
    7: var filtersUrl = <%= raw_json queries_filter_path(:project_id => @query.project.try(:id), :type => @query.type) %>;
  app/models/query.rb:464:in `block in available_filters_as_json'
  app/models/query.rb:462:in `each'
  app/models/query.rb:462:in `available_filters_as_json'
  app/views/queries/_filters.html.erb:4:in `block in _app_views_queries__filters_html_erb___218005857970535534_70206203145280'
  app/views/queries/_filters.html.erb:1:in `_app_views_queries__filters_html_erb___218005857970535534_70206203145280'
  app/views/queries/_query_form.html.erb:10:in `_app_views_queries__query_form_html_erb__4133403555005295366_70206203058420'
  app/views/timelog/_date_range.html.erb:1:in `_app_views_timelog__date_range_html_erb__3845577496136492909_70206203018520'
  app/views/timelog/index.html.erb:10:in `block in _app_views_timelog_index_html_erb__4526196220538483806_70206202905200'
  app/views/timelog/index.html.erb:9:in `_app_views_timelog_index_html_erb__4526196220538483806_70206202905200'
  app/controllers/timelog_controller.rb:54:in `block (2 levels) in index'
  app/controllers/timelog_controller.rb:48:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
My **environment**:
```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Cvs                            1.12.13
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.4
  redmine_ckeditor               1.1.5
  redmine_gitlab_hook            0.1.3
  redmine_tagging                0.1.6
```
PS: Also happens when using redmine_tagging v0.1.5 release
