### ISSUE TITLE
error on redmine 3.3.1

### ISSUE THREAD

**Issue by avtora** [Restream/redmine_tagging#80]
It did not work on redmine 3.3.x with some top plugins..

error log
```
/usr/share/redmine/plugins/redmine_tagging/lib/redmine_tagging/patches/query_patch.rb:48:in `available_tags_filter'
/usr/share/redmine/plugins/redmine_tagging/lib/redmine_tagging/patches/query_patch.rb:19:in `available_filters_with_tags'
/usr/share/redmine/plugins/extra_queries/lib/extra_queries/issue_query_patch.rb:174:in `available_filters_with_eq'
/usr/share/redmine/plugins/unread_issues/lib/unread_issues/issue_query_patch.rb:104:in `available_filters_with_uis'
/usr/share/redmine/app/models/query.rb:408:in `type_for'
/usr/share/redmine/app/models/query.rb:265:in `block in validate_query_filters'
/usr/share/redmine/app/models/query.rb:263:in `each_key'
/usr/share/redmine/app/models/query.rb:263:in `validate_query_filters'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:192:in `block in simple'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_validate_callbacks'
/usr/lib/ruby/vendor_ruby/active_model/validations.rb:399:in `run_validations!'
/usr/lib/ruby/vendor_ruby/active_model/validations/callbacks.rb:113:in `block in run_validations!'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/usr/lib/ruby/vendor_ruby/active_model/validations/callbacks.rb:113:in `run_validations!'
/usr/lib/ruby/vendor_ruby/active_model/validations.rb:338:in `valid?'
/usr/lib/ruby/vendor_ruby/active_record/validations.rb:58:in `valid?'
/usr/share/redmine/app/models/query.rb:629:in `statement'
/usr/share/redmine/app/models/issue_query.rb:381:in `issue_ids'
/usr/share/redmine/plugins/unread_issues/lib/unread_issues/issue_query_patch.rb:34:in `issue_ids_with_uis'
/usr/share/redmine/plugins/unread_issues/lib/unread_issues/user_patch.rb:76:in `ui_issues_counts'
/usr/share/redmine/plugins/unread_issues/lib/unread_issues/user_patch.rb:34:in `my_page_counts'
/usr/share/redmine/plugins/unread_issues/lib/unread_issues/user_patch.rb:23:in `my_issues_caption'
/usr/share/redmine/plugins/unread_issues/init.rb:20:in `block (2 levels) in <top (required)>'
/usr/share/redmine/lib/redmine/menu_manager.rb:417:in `caption'
/usr/share/redmine/plugins/custom_menu/lib/custom_menu/menu_item_patch.rb:16:in `caption_with_cm'
/usr/share/redmine/lib/redmine/menu_manager.rb:197:in `extract_node_details'
/usr/share/redmine/plugins/redmine_cms/lib/redmine_cms/patches/menu_manager_patch.rb:27:in `render_menu_node'
/usr/share/redmine/lib/redmine/menu_manager.rb:91:in `block in render_menu'
/usr/share/redmine/lib/redmine/menu_manager.rb:174:in `block in menu_items_for'
/usr/share/redmine/lib/redmine/menu_manager.rb:171:in `each'
/usr/share/redmine/lib/redmine/menu_manager.rb:171:in `menu_items_for'
/usr/share/redmine/lib/redmine/menu_manager.rb:90:in `render_menu'
/usr/share/redmine/plugins/custom_menu/lib/custom_menu/menu_helper_patch.rb:79:in `render_menu_with_custom_menu'
/usr/share/redmine/app/views/layouts/base.html.erb:66:in `_app_views_layouts_base_html_erb___2898648078607581122_70336405815340'
/usr/lib/ruby/vendor_ruby/action_view/template.rb:145:in `block in render'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:166:in `instrument'
/usr/lib/ruby/vendor_ruby/action_view/template.rb:333:in `instrument'
/usr/lib/ruby/vendor_ruby/action_view/template.rb:143:in `render'
/usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
/usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:52:in `render_template'
/usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:14:in `render'
/usr/lib/ruby/vendor_ruby/action_view/renderer/renderer.rb:46:in `render_template'
/usr/lib/ruby/vendor_ruby/action_view/renderer/renderer.rb:27:in `render'
/usr/lib/ruby/vendor_ruby/action_view/rendering.rb:100:in `_render_template'
/usr/lib/ruby/vendor_ruby/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/lib/ruby/vendor_ruby/action_view/rendering.rb:83:in `render_to_body'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:32:in `render_to_body'
/usr/lib/ruby/vendor_ruby/action_controller/metal/renderers.rb:37:in `render_to_body'
/usr/lib/ruby/vendor_ruby/abstract_controller/rendering.rb:25:in `render'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:16:in `render'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/lib/ruby/vendor_ruby/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/vendor_ruby/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:43:in `render'
/usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:10:in `default_render'
/usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:5:in `send_action'
/usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:198:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:10:in `process_action'
/usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:117:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:505:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/share/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:312:in `block in halting'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:497:in `block in around'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:505:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:19:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rescue.rb:29:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:164:in `block in instrument'
/usr/lib/ruby/vendor_ruby/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:164:in `instrument'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:137:in `process'
/usr/lib/ruby/vendor_ruby/action_view/rendering.rb:30:in `process'
/usr/lib/ruby/vendor_ruby/action_controller/metal.rb:196:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_controller/metal.rb:237:in `block in action'
/usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:30:in `each'
/usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:30:in `serve'
/usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:817:in `call'
/var/lib/gems/2.3.0/gems/rack-raw-upload-1.1.1/lib/rack/raw_upload.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/flash.rb:260:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:36:in `call'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
/usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:26:in `tagged'
/usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `tagged'
/usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `call'
/var/lib/gems/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:120:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:518:in `call'
/usr/lib/ruby/vendor_ruby/rails/application.rb:165:in `call'
/usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `public_send'
/usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.2
  bestest_timer                  1.1.2
  custom_menu                    1.7.4
  event_notifications            3.2.1
  extra_queries                  2.2.9
  global_roles                   2.2.0
  redmine_agile                  1.4.4
  redmine_checklists             3.1.6
  redmine_ckeditor               1.1.5
  redmine_cms                    1.0.1
  redmine_drawio                 0.8.0
  redmine_hotkeys_js             0.0.5
  redmine_impersonate            0.10.0
  redmine_issue_badge            0.0.6
  redmine_issue_tabs             1.2.3
  redmine_people                 1.3.1
  redmine_private_wiki           0.2.0
  redmine_questions              0.0.7
  redmine_wiki_extensions        0.7.0
  redmine_wiki_nav_sidebar       1.0
  redmine_work_time              0.3.4
  redmineup_tags                 2.0.0
  time_logger                    0.5.4
  unread_issues                  2.1.2
  usability                      2.2.5
  view_customize                 1.1.4
```

**Comment by avtora** [comment]
After removing plugins redmine stared but when I try to get issue page:

**Error log**
```
/usr/share/redmine/plugins/redmine_tagging/lib/redmine_tagging/patches/query_patch.rb:48:in `available_tags_filter'
/usr/share/redmine/plugins/redmine_tagging/lib/redmine_tagging/patches/query_patch.rb:19:in `available_filters_with_tags'
/usr/share/redmine/app/models/query.rb:247:in `build_from_params'
/usr/share/redmine/app/models/issue_query.rb:124:in `build_from_params'
/usr/share/redmine/app/helpers/queries_helper.rb:227:in `retrieve_query'
/usr/share/redmine/app/controllers/issues_controller.rb:45:in `index'
/usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:198:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:10:in `process_action'
/usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:117:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:505:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/share/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:312:in `block in halting'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:497:in `block in around'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:505:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:19:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rescue.rb:29:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:164:in `block in instrument'
/usr/lib/ruby/vendor_ruby/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:164:in `instrument'
/usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/lib/ruby/vendor_ruby/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:137:in `process'
/usr/lib/ruby/vendor_ruby/action_view/rendering.rb:30:in `process'
/usr/lib/ruby/vendor_ruby/action_controller/metal.rb:196:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_controller/metal.rb:237:in `block in action'
/usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:30:in `each'
/usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:30:in `serve'
/usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:817:in `call'
/var/lib/gems/2.3.0/gems/rack-raw-upload-1.1.1/lib/rack/raw_upload.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/flash.rb:260:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:36:in `call'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
/usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:26:in `tagged'
/usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `tagged'
/usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `call'
/var/lib/gems/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:120:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:518:in `call'
/usr/lib/ruby/vendor_ruby/rails/application.rb:165:in `call'
/usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `public_send'
/usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```
